import type { Metadata } from "next";
import { CopilotKit } from "@copilotkit/react-core";
import { CopilotPopup } from "@copilotkit/react-ui";
import localFont from "next/font/local";
import { COPILOTKIT_API_ENDPOINT } from "@/lib/constants";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CopilotKit
          runtimeUrl={COPILOTKIT_API_ENDPOINT}
          //publicApiKey={env.COPILOTKIT_PUBLIC_KEY}
        >
          {children}
          <CopilotPopup />
        </CopilotKit>
      </body>
    </html>
  );
}
